---
title: "UCLA Herbarium Specimen Analysis"
author: "Ryan Quach"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data importation 

```{r}
herbarium_data <- data.table::fread("/Users/ryanquach/herbarium/occurrences.csv")
```

## Data wrangling 

```{r}
herbarium_data <- herbarium_data %>%
  rename(coord_uncertainty = coordinateUncertaintyInMeters,
         min_elevation = minimumElevationInMeters,
         longitude = decimalLongitude, latitude = decimalLatitude) %>%
  janitor::remove_empty(which = "cols")
```

## Data visualization

```{r}
par(mar = c(6, 8, 6, 6))
```

```{r}
fam_freq <- table(herbarium_data$family) %>%
  sort(decreasing = TRUE) %>%
  .[-1] %>%
  .[seq_len(10)] %>%
  sort(decreasing = FALSE)
```

```{r}
barplot(fam_freq, horiz = TRUE,
        col = "darkgreen", 
        density = 50, angle = 45,
        cex.names = 0.50, las = 2,
        main = "Ten most common families and their respective frequencies")
```

```{r}
par(mar = c(8, 6, 6, 6))
```

```{r}
genera_freq <- table(herbarium_data$genus) %>%
  sort(decreasing = TRUE) %>%
  .[-1] %>%
  .[seq_len(10)] %>%
  sort(decreasing = FALSE)
```

```{r}
barplot(genera_freq, horiz = TRUE,
        col = "darkgreen", 
        density = 50, angle = -45,
        cex.names = 0.70, las = 2,
        main = "Ten most common genera and their respective frequencies")
```

```{r}
year_data <- herbarium_data %>%
  select(year) %>%
  filter(year > 1800)

summary(year_data$year)
```

```{r}
hist(year_data$year, 
     col = "darkgreen",
     density = 55, angle = 45,
     main = "Number of specimens by year",
     xlab = "Year")
```


```{r}
hist(herbarium_data$coord_uncertainty, 
     col = "#159e46",
     density = 45, angle = -45,
     main = "Coordinate uncertainty in meters",
     xlab = "Meters")
```

```{r}
hist(herbarium_data$coord_uncertainty[herbarium_data$coord_uncertainty <= 10000], 
     col = "#159e46",
     density = 45, angle = -45,
     main = "Coordinate uncertainty in meters without outliers",
     xlab = "Meters")
```

```{r}
hist(herbarium_data$min_elevation,
     col = "#bf462e",
     density = 55, angle = 45,
     main = "Minimum elevation in meters among the botanical specimens",
     xlab = "Meters")
```

## Mapping specimen locations

```{r}
library(mapview)
library(sf)
```

```{r}
herb_sf <- herbarium_data %>%
  filter(!is.na(longitude), !is.na(latitude), !is.na(min_elevation)) %>%
  select(scientificName, min_elevation, recordedBy, eventDate,
         county, longitude, latitude) %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)
```


```{r}
world <- st_as_sf(maps::map("world", plot = FALSE, fill = TRUE), crs = 4326)
states <- st_as_sf(maps::map("state", plot = FALSE, fill = TRUE), crs = 4326)

ggplot() +
  geom_sf(data = world) +
  geom_sf(data = states) +
  geom_sf(data = herb_sf, alpha = 0.5) +
  coord_sf(xlim = c(-125, -112), ylim = c(30, 45), expand = FALSE)
```

Note that the "world" layer is used for the purpose of adding the Mexican borders. 

```{r}
mapview(herb_sf)
```

IDEA FOR A MODEL: ARE CERTAIN FAMILIES/SPECIES MORE LIKELY TO BE FOUND IN CERTAIN SEASONS?


